import 'package:flutter/foundation.dart';
import '../models/product.dart';
import 'partner_provider.dart';

class ProductProvider with ChangeNotifier {
  PartnerProvider? _partnerProvider;

  void setPartnerProvider(PartnerProvider partnerProvider) {
    _partnerProvider = partnerProvider;
  }

  final List<Product> _items = [
    Product(
      id: 'p1',
      name: 'Royal Canin Maxi Adult',
      description: 'Сухой корм для взрослых собак крупных пород. Укрепляет суставы и поддерживает оптимальный вес.',
      price: 25500,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=500&q=80',
      rating: 4.8,
    ),
    Product(
      id: 'p2',
      name: 'Purina Pro Plan Sterilised',
      description: 'Сухой корм для стерилизованных кошек с лососем. Поддерживает здоровье почек.',
      price: 8500,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=500&q=80',
      rating: 4.8,
    ),
    Product(
      id: 'p3',
      name: 'Whiskas Вкусные подушечки',
      description: 'Корм с говядиной и морковью для кошек. Хрустящие подушечки с нежным паштетом.',
      price: 1200,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?w=500&q=80',
      rating: 4.3,
    ),
    Product(
      id: 'p4',
      name: 'Pedigree для взрослых собак',
      description: 'Полнорационный корм для собак всех пород с говядиной и птицей.',
      price: 13400,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=500&q=80',
      rating: 5.0,
    ),
    Product(
      id: 'p5',
      name: 'Acana Grass-Fed Lamb',
      description: 'Гипоаллергенный корм с мясом ягненка для собак всех пород.',
      price: 34000,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p6',
      name: 'Orijen Six Fish',
      description: 'Биологически соответствующий корм для кошек с 6 видами рыбы.',
      price: 41000,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&q=80',
      rating: 4.7,
    ),
    Product(
      id: 'p7',
      name: 'Felix Мясные кусочки',
      description: 'Влажный корм для кошек в желе с ягненком и курицей.',
      price: 250,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p8',
      name: 'Brit Care Adult Medium',
      description: 'Гипоаллергенный корм с уткой и рисом для собак средних пород.',
      price: 21500,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=500&q=80',
      rating: 4.7,
    ),
    Product(
      id: 'p9',
      name: 'Monge Dog Monoprotein',
      description: 'Комплексный корм с кроликом, рисом и картофелем.',
      price: 18900,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=500&q=80',
      rating: 4.6,
    ),
    Product(
      id: 'p10',
      name: "Hill's Science Plan",
      description: 'Корм для котят с курицей. Идеален для роста и развития.',
      price: 9500,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=500&q=80',
      rating: 4.4,
    ),
    Product(
      id: 'p11',
      name: 'Grandorf Indoor Cat',
      description: 'Корм холистик-класса с индейкой и бурым рисом.',
      price: 14500,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p12',
      name: 'Kitekat с говядиной',
      description: 'Консервированный корм для кошек (пауч).',
      price: 180,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=500&q=80',
      rating: 4.0,
    ),
    Product(
      id: 'p13',
      name: 'Chappi Мясной пир',
      description: 'Сухой корм для активных собак.',
      price: 7800,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80',
      rating: 4.7,
    ),
    Product(
      id: 'p14',
      name: '1st Choice Adult',
      description: 'Корм для кошек с чувствительным пищеварением.',
      price: 11200,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=500&q=80',
      rating: 4.5,
    ),
    Product(
      id: 'p15',
      name: 'Royal Canin Kitten',
      description: 'Сухой корм для котят до 12 месяцев. Легко усваивается.',
      price: 12500,
      category: 'Тамақ',
      imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p16',
      name: 'Удочка-дразнилка с перьями',
      description: 'Интерактивная игрушка для активных кошек. Пробуждает охотничий инстинкт.',
      price: 1500,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=500&q=80',
      rating: 4.7,
    ),
    Product(
      id: 'p17',
      name: 'Мячик резиновый с шипами',
      description: 'Отличный мяч для массажа десен собак и долгих игр на улице.',
      price: 1200,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=500&q=80',
      rating: 4.4,
    ),
    Product(
      id: 'p18',
      name: 'Когтеточка столбик',
      description: 'Классическая когтеточка из сизаля с игрушкой-мышкой на резинке.',
      price: 8500,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1611003229186-5c477b665b1b?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p19',
      name: 'Пуллер (Puller) стандарт',
      description: 'Тренировочный снаряд для собак. Легкий и безопасный для зубов.',
      price: 5500,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&q=80',
      rating: 4.4,
    ),
    Product(
      id: 'p20',
      name: 'Мышка плюшевая с мятой',
      description: 'Мягкая мышка с кошачьей мятой внутри для привлечения внимания.',
      price: 800,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=500&q=80',
      rating: 4.9,
    ),
    Product(
      id: 'p21',
      name: 'Интерактивная кормушка Kong',
      description: 'Игрушка под лакомства. Занимает собаку на долгое время.',
      price: 6500,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=500&q=80',
      rating: 4.7,
    ),
    Product(
      id: 'p22',
      name: 'Лазерная указка',
      description: 'Классическая игрушка для кошек. Несколько режимов свечения.',
      price: 1100,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?w=500&q=80',
      rating: 4.1,
    ),
    Product(
      id: 'p23',
      name: 'Фрисби для собак',
      description: 'Летающая тарелка из прочного и безопасного материала.',
      price: 2300,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=500&q=80',
      rating: 4.0,
    ),
    Product(
      id: 'p24',
      name: 'Канат для перетягивания',
      description: 'Прочный канат с двумя узлами для активных игр с собакой.',
      price: 1800,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=500&q=80',
      rating: 4.3,
    ),
    Product(
      id: 'p25',
      name: 'Мягкая игрушка с пищалкой',
      description: 'Собачья игрушка-енот. Издает звук при нажатии.',
      price: 2900,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&q=80',
      rating: 4.7,
    ),
    Product(
      id: 'p26',
      name: 'Кольцо резиновое Trixie',
      description: 'Универсальная игрушка для аппортировки.',
      price: 1400,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1560743641-3914f2c45636?w=500&q=80',
      rating: 4.7,
    ),
    Product(
      id: 'p27',
      name: 'Тоннель для кошек',
      description: 'Складной шуршащий тоннель с тремя выходами.',
      price: 4500,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=500&q=80',
      rating: 4.6,
    ),
    Product(
      id: 'p28',
      name: 'Развивающая головоломка',
      description: 'Игрушка-пазл для собак для развития интеллекта.',
      price: 7500,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p29',
      name: 'Трек с шариками',
      description: 'Трехъярусный трек для кошек с звенящими шариками.',
      price: 5200,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&q=80',
      rating: 4.4,
    ),
    Product(
      id: 'p30',
      name: 'Светящийся мяч LED',
      description: 'Мяч, который светится при ударе. Идеально для ночных прогулок.',
      price: 3100,
      category: 'Ойыншықтар',
      imageUrl: 'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p31',
      name: 'Поводок-рулетка Flexi 5м',
      description: 'Надежный поводок ленточного типа для собак до 15 кг.',
      price: 6800,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=500&q=80',
      rating: 4.8,
    ),
    Product(
      id: 'p32',
      name: 'Ошейник светящийся USB',
      description: 'LED ошейник для безопасных прогулок в темноте. Заряжается от USB.',
      price: 2500,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
      rating: 4.7,
    ),
    Product(
      id: 'p33',
      name: 'Миска керамическая',
      description: 'Тяжелая и устойчивая миска для кошек и собак. Легко мыть.',
      price: 3200,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=500&q=80',
      rating: 4.4,
    ),
    Product(
      id: 'p34',
      name: 'Шлейка анатомическая',
      description: 'Комфортная мягкая шлейка, не давящая на шею собаки.',
      price: 5500,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p35',
      name: 'Лежанка пушистая антистресс',
      description: 'Мягкая круглая лежанка для глубокого сна питомцев.',
      price: 8900,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=500&q=80',
      rating: 4.3,
    ),
    Product(
      id: 'p36',
      name: 'Рюкзак-переноска с иллюминатором',
      description: 'Стильный рюкзак для транспортировки кошек.',
      price: 12500,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=500&q=80',
      rating: 4.8,
    ),
    Product(
      id: 'p37',
      name: 'Переноска пластиковая Skudo',
      description: 'Надежная переноска стандарта IATA для авиаперелетов.',
      price: 17000,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&q=80',
      rating: 4.3,
    ),
    Product(
      id: 'p38',
      name: 'Автопоилка-фонтан',
      description: 'Фонтанчик для кошек. Побуждает пить больше чистой воды.',
      price: 11500,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=500&q=80',
      rating: 4.2,
    ),
    Product(
      id: 'p39',
      name: 'Металлическая миска на подставке',
      description: 'Две миски на регулируемой по высоте подставке.',
      price: 7500,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=500&q=80',
      rating: 4.8,
    ),
    Product(
      id: 'p40',
      name: 'Адресник-капсула',
      description: 'Металлический блестящий адресник для записки с номером владельца.',
      price: 800,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=500&q=80',
      rating: 4.3,
    ),
    Product(
      id: 'p41',
      name: 'Автокормушка',
      description: 'Умная кормушка с таймером на 4 кормления.',
      price: 19000,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=500&q=80',
      rating: 4.9,
    ),
    Product(
      id: 'p42',
      name: 'Силиконовый коврик под миски',
      description: 'Защищает пол от брызг воды и крошек корма.',
      price: 2200,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1560743641-3914f2c45636?w=500&q=80',
      rating: 4.8,
    ),
    Product(
      id: 'p43',
      name: 'Намордник кожаный Basket',
      description: 'Удобный и прочный намордник для средних и крупных пород.',
      price: 4500,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&q=80',
      rating: 4.8,
    ),
    Product(
      id: 'p44',
      name: 'Ошейник кожаный Trixie',
      description: 'Классический кожаный ошейник с металлическими заклепками.',
      price: 3800,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
      rating: 4.8,
    ),
    Product(
      id: 'p45',
      name: 'Лесенка для мелких собак',
      description: 'Трехступенчатая лесенка для безопасного подъема на диван.',
      price: 9500,
      category: 'Аксессуарлар',
      imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=500&q=80',
      rating: 4.6,
    ),
    Product(
      id: 'p46',
      name: 'Наполнитель силикагелевый 5л',
      description: 'Отлично впитывает влагу и полностью блокирует запах.',
      price: 4500,
      category: 'Гигиена',
      imageUrl: 'https://basket-10.wbbasket.ru/vol1388/part138847/138847941/images/big/1.webp',
      rating: 4.6,
    ),
    Product(
      id: 'p47',
      name: 'Шампунь для длинношерстных собак',
      description: 'Облегчает расчесывание и придает шерсти здоровый блеск.',
      price: 3200,
      category: 'Гигиена',
      imageUrl: 'https://ir.ozone.ru/s3/multimedia-1-e/c1000/7476477530.jpg',
      rating: 4.0,
    ),
    Product(
      id: 'p48',
      name: 'Лоток закрытый с фильтром',
      description: 'Лоток-домик. Предотвращает разбрасывание наполнителя.',
      price: 14500,
      category: 'Гигиена',
      imageUrl: 'https://basket-10.wbbasket.ru/vol1358/part135817/135817796/images/c516x688/1.webp',
      rating: 4.7,
    ),
    Product(
      id: 'p49',
      name: 'Древесный наполнитель 15кг',
      description: 'Натуральный и экологичный. Подходит для смывания в туалет.',
      price: 2800,
      category: 'Гигиена',
      imageUrl: 'https://ir.ozone.ru/s3/multimedia-m/c1000/6603325618.jpg',
      rating: 4.8,
    ),
    Product(
      id: 'p50',
      name: 'Пеленки впитывающие 60х60',
      description: 'Упаковка 30 шт. Идеально для щенков и приучения к туалету.',
      price: 4100,
      category: 'Гигиена',
      imageUrl: 'https://goods-photos.static1-sima-land.com/items/2413087/0/700-nw.jpg',
      rating: 5.0,
    ),
    Product(
      id: 'p51',
      name: 'Бентонитовый наполнитель (комкующийся)',
      description: 'Быстро образует плотные комочки, легко убирать.',
      price: 3600,
      category: 'Гигиена',
      imageUrl: 'https://ir.ozone.ru/s3/multimedia-1-7/c1000/7258388875.jpg',
      rating: 4.7,
    ),
    Product(
      id: 'p52',
      name: 'Фурминатор (дешеддер)',
      description: 'Инструмент против линьки. Удаляет до 90% отмершего подшерстка.',
      price: 6500,
      category: 'Гигиена',
      imageUrl: 'https://basket-17.wbbasket.ru/vol2819/part281926/281926768/images/c516x688/1.webp',
      rating: 4.4,
    ),
    Product(
      id: 'p53',
      name: 'Когтерез-секатор с ограничителем',
      description: 'Острые ножницы для безопасной стрижки когтей.',
      price: 2100,
      category: 'Гигиена',
      imageUrl: 'https://ir.ozone.ru/s3/multimedia-r/c1000/6367259175.jpg',
      rating: 4.1,
    ),
    Product(
      id: 'p54',
      name: 'Лосьон для чистки ушей',
      description: 'Мягко очищает ушную раковину собак и кошек.',
      price: 1800,
      category: 'Гигиена',
      imageUrl: 'https://www.zootovar-spb.ru/images/34/42/344284.jpg',
      rating: 4.0,
    ),
    Product(
      id: 'p55',
      name: 'Зубная паста и щетка',
      description: 'Набор для ухода за зубами собак со вкусом говядины.',
      price: 2400,
      category: 'Гигиена',
      imageUrl: 'https://ir.ozone.ru/s3/multimedia-3/6777825087.jpg',
      rating: 4.4,
    ),
    Product(
      id: 'p56',
      name: 'Спрей "Антигадин"',
      description: 'Отучает питомца гадить в неположенных местах.',
      price: 1900,
      category: 'Гигиена',
      imageUrl: 'https://ir.ozone.ru/s3/multimedia-7/c1000/6426533119.jpg',
      rating: 4.8,
    ),
    Product(
      id: 'p57',
      name: 'Спрей для уничтожения запаха',
      description: 'Энзимный спрей для удаления пятен мочи и запаха.',
      price: 2600,
      category: 'Гигиена',
      imageUrl: 'https://ir.ozone.ru/s3/multimedia-1-p/c1000/7266739669.jpg',
      rating: 4.2,
    ),
    Product(
      id: 'p58',
      name: 'Салфетки очищающие для лап',
      description: 'Влажные салфетки, безопасные для животных. 50 шт.',
      price: 1100,
      category: 'Гигиена',
      imageUrl: 'https://image.made-in-china.com/202f0j00wQjoZYyWLkgq/Circular-Shape-for-Cleaning-Animals-Paws-and-Nose-and-Ears-Pet-Wet-Wipes.webp',
      rating: 5.0,
    ),
    Product(
      id: 'p59',
      name: 'Расческа-пуходерка',
      description: 'Сликер с каплями на зубчиках для бережного вычесывания.',
      price: 1500,
      category: 'Гигиена',
      imageUrl: 'https://claws.com.ua/wp-content/uploads/2015/01/comb_soft.jpg',
      rating: 4.2,
    ),
    Product(
      id: 'p60',
      name: 'Шампунь без слез для котят',
      description: 'Гипоаллергенный мягкий шампунь.',
      price: 2800,
      category: 'Гигиена',
      imageUrl: 'https://avatars.mds.yandex.net/get-mpic/16508997/2a00000198a0fcdd39e16bd7e5cacc30c06a/orig',
      rating: 4.3,
    ),
    Product(
      id: 'p61',
      name: 'Дождевик желтый',
      description: 'Водонепроницаемый комбинезон-дождевик с капюшоном.',
      price: 6500,
      category: 'Киімдер',
      imageUrl: 'https://catalog-cdn.detmir.st/media/dtDUGDNKqIGu5F4Qf0xpzxhnxZJw8OfbK84AOxWuzw0=.jpeg',
      rating: 4.9,
    ),
    Product(
      id: 'p62',
      name: 'Свитер вязаный "Скандинавия"',
      description: 'Теплый свитер с орнаментом для собак мелких пород.',
      price: 5200,
      category: 'Киімдер',
      imageUrl: 'https://vip-dog.com/image/cache/catalog/Tovary/Kofty/57abc99a19ebf4e79266945883a6763d-550x550.jpg',
      rating: 4.2,
    ),
    Product(
      id: 'p63',
      name: 'Комбинезон зимний на флисе',
      description: 'Утепленный комбинезон для сильных морозов.',
      price: 11500,
      category: 'Киімдер',
      imageUrl: 'https://ir.ozone.ru/s3/multimedia-l/c1000/6105155553.jpg',
      rating: 4.7,
    ),
    Product(
      id: 'p64',
      name: 'Ботиночки непромокаемые',
      description: 'Защищают лапы от реагентов и льда зимой (комплект 4 шт).',
      price: 4800,
      category: 'Киімдер',
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS67FhTpcQYQwFRTWwpugg79mk8vuncstvVgg&s',
      rating: 4.0,
    ),
    Product(
      id: 'p65',
      name: 'Футболка летняя Boss',
      description: 'Легкая хлопковая майка для защиты от солнца.',
      price: 2500,
      category: 'Киімдер',
      imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
      rating: 4.9,
    ),
    Product(
      id: 'p66',
      name: 'Толстовка с капюшоном Adidog',
      description: 'Модная спортивная толстовка для стильных собак.',
      price: 3500,
      category: 'Киімдер',
      imageUrl: 'https://i.ebayimg.com/images/g/GBcAAOSwO9JmjH5X/s-l1200.webp',
      rating: 4.8,
    ),
    Product(
      id: 'p67',
      name: 'Платье кружевное',
      description: 'Нарядное платье для особых случаев (для мелких собачек).',
      price: 4200,
      category: 'Киімдер',
      imageUrl: 'https://ae04.alicdn.com/kf/S57aad23eb4b744bb85bc85cf55b346eeV.jpg',
      rating: 4.4,
    ),
    Product(
      id: 'p68',
      name: 'Жилет сигнальный (светоотражающий)',
      description: 'Обеспечивает безопасность в темное время суток.',
      price: 1800,
      category: 'Киімдер',
      imageUrl: 'https://basket-04.wbbasket.ru/vol590/part59087/59087795/images/c516x688/1.webp',
      rating: 4.0,
    ),
    Product(
      id: 'p69',
      name: 'Попона послеоперационная',
      description: 'Дышащая попона для кошек и собак.',
      price: 2100,
      category: 'Киімдер',
      imageUrl: 'https://resources.cdn-kaspi.kz/img/m/p/h4a/hb3/85395781320734.png?format=gallery-large',
      rating: 4.6,
    ),
    Product(
      id: 'p70',
      name: 'Носочки антискользящие',
      description: 'С силиконовым покрытием, чтобы лапы не скользили по ламинату.',
      price: 1200,
      category: 'Киімдер',
      imageUrl: 'https://avatars.mds.yandex.net/get-mpic/4410238/2a00000199a6c491dcf2045c6ffe5ba98459/orig',
      rating: 4.6,
    ),
    Product(
      id: 'p71',
      name: 'Бандана на ошейник',
      description: 'Яркий аксессуар для стильной прогулки.',
      price: 900,
      category: 'Киімдер',
      imageUrl: 'https://ae01.alicdn.com/kf/S55dbf073788340749cb8c4a063763ad8j.jpg?width=800&height=800&hash=1600',
      rating: 4.6,
    ),
    Product(
      id: 'p72',
      name: 'Кепка от солнца с прорезями для ушей',
      description: 'Защищает глаза питомца. Фиксируется под подбородком.',
      price: 1600,
      category: 'Киімдер',
      imageUrl: 'https://ae04.alicdn.com/kf/Sb12bed7c34d747c5b91006172ab25544n.jpg',
      rating: 4.1,
    ),
    Product(
      id: 'p73',
      name: 'Снуд-шарф',
      description: 'Защищает длинные уши от попадания в миску и от холода.',
      price: 2200,
      category: 'Киімдер',
      imageUrl: 'https://markvet.ru/upload/iblock/6f3/12h6wwzgquihl2kdkxenqfkr4ndxlqzr.jpg',
      rating: 4.2,
    ),
    Product(
      id: 'p74',
      name: 'Халат банный из микрофибры',
      description: 'Отлично впитывает воду после мытья.',
      price: 5500,
      category: 'Киімдер',
      imageUrl: 'https://www.zoofashion.ru/upload/iblock/487/efbdv7y50n02szftdt4sly1h9q33xoae.jpg',
      rating: 4.4,
    ),
    Product(
      id: 'p75',
      name: 'Костюм Деда Мороза',
      description: 'Праздничный наряд для питомца к Новому году.',
      price: 4500,
      category: 'Киімдер',
      imageUrl: 'https://image.kazanexpress.ru/ctnu08fd16b9lm2b19mg/feedback_40.jpg',
      rating: 4.9,
    ),
  ];

  List<Product> get items {
    final partnerProducts = _partnerProvider?.products
        .where((p) => p.isActive)
        .map((p) => p.toProduct())
        .toList() ?? [];
    return [..._items, ...partnerProducts];
  }

  /// Проверяет, является ли товар партнёрским
  bool isPartnerProduct(String id) {
    return _partnerProvider?.products.any((p) => p.id == id) ?? false;
  }

  List<Product> getProductsByCategory(String category) {
    if (category == 'Барлығы') return items;
    return items.where((prod) => prod.category == category).toList();
  }

  Product findById(String id) {
    return items.firstWhere((prod) => prod.id == id);
  }

  List<Product> search(String query) {
    if (query.isEmpty) return items;
    return items.where((prod) => prod.name.toLowerCase().contains(query.toLowerCase())).toList();
  }
}
